project_id = "daaszrjhoqxxjhhmxouk"

[functions.generate-messages]
verify_jwt = false

[functions.send-messages]
verify_jwt = false

[functions.crm-webhook]
verify_jwt = false

[functions.paypal-setup]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.paypal-create-subscription]
verify_jwt = false

[functions.paypal-config]
verify_jwt = false
